### ISSUE TITLE
ArgumentCountError - Too few arguments to function Symfony\Bridge\Twig\Extension\FormExtension::__construct(), 0 passed in /data/shop/development/current/vendor/spryker/silexphp/src/Silex/Provider/TwigServiceProvider.php on line 93 

### ISSUE THREAD

**Issue by ckdot** [spryker/silexphp#6]
One of the requirements of spryker/silexphp is:
- "symfony/twig-bridge": "~2.3|3.0.*"

_symfony/twig-bridge_ 2.3 - 3.1 requires an instance of _Symfony\Bridge\Twig\Form\TwigRendererInterface_ in the constructor of _FormExtension_ which is not passed in _/data/shop/development/current/vendor/spryker/silexphp/src/Silex/Provider/TwigServiceProvider.php_ on line 93.

**Comment by stereomon** [comment]
Hello Christian,

we fixed this issue already here https://github.com/spryker/symfony/releases/tag/3.2.1. Please make sure that you updated to this version.

The constraint in this package to "symfony/twig-bridge": "~2.3|3.0.*" is only a require-dev dependency we also updated. 

Please, follow the instructions on this page https://github.com/spryker/support and do not add issues to the repositories directly. Thank you!
