### ISSUE TITLE
Deprecation warning in TwigServiceProvider.php

### ISSUE THREAD

**Issue by ckdot** [spryker/silexphp#7]
Deprecation warning of class says:
`@deprecated Please add Spryker\Shared\Twig\Service\TwigServiceProvider to your ApplicationDependencyProvider::getServices() to replace this one.`

-  Spryker\Shared\Twig\Service\TwigServiceProvider  doesn't seem to exist, even in newest spryker/twig
- Method getServices() doesn't exist in ApplicationDependencyProvider; probably getServiceProviders() is meant?

**Comment by stereomon** [comment]
Hello Christian,

we removed the too early added deprecation warnings in this release https://github.com/spryker/silexphp/releases/tag/0.1.2.

Please update to this version.

Please, follow the instructions on this page https://github.com/spryker/support and do not add issues to the repositories directly. Thank you!
